name = "issuer"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV"
# id = "462dd4a8b36543fcaecab1ffa81d3135"
# preview_id = "d59ec1b11bf0414390cd2a7b6dc18cc3"
[[kv_namespaces]]
binding = "_Session"
id = "280b8aa6cefc409d9617cf5b40a87c0c"
preview_id = "9665edc832e94786ab8a6cafeabd2789"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [triggers]
# crons = ["0 */1 * * *","59 23 LW * *","*/3 * * * *"]
